import type { Language } from "@/i18n/languagePreference";

// English is the source text. Every phrase has reviewed Swedish, Spanish,
// French and Simplified Chinese text; there is no per-phrase English fallback.
export const tradingPhrases = {
  "Exact word in the curated vocabulary": ["Exakt ord i den granskade ordlistan", "Palabra exacta del vocabulario revisado", "Mot exact du vocabulaire sélectionné", "与精选词库中的词完全匹配"],
  "Two words with a shared application": ["Två ord med gemensamt användningsområde", "Dos palabras con un uso común", "Deux mots associés à un même usage", "两个词有共同的用途"],
  "Descriptive word without a clear service": ["Beskrivande ord utan tydlig tjänst", "Palabra descriptiva sin un servicio definido", "Mot descriptif sans service clairement associé", "描述性词语，未指向明确服务"],
  "The word pair has no clear shared application": ["Ordparets användningsområde är oklart", "Las dos palabras no tienen un uso conjunto claro", "Les deux mots n’ont pas d’usage commun évident", "两个词的组合用途不明确"],
  "Words from different languages": ["Ord från olika språk", "Palabras de idiomas distintos", "Mots issus de langues différentes", "词语来自不同语言"],
  "The vocabulary does not cover this name": ["Namnet täcks inte av ordlistan", "El vocabulario no incluye este nombre", "Ce nom ne figure pas dans le vocabulaire", "词库未覆盖此名称"],
  "Only part of the name matches a known word": ["Endast en del av namnet matchar ett känt ord", "Solo parte del nombre coincide con una palabra conocida", "Seule une partie du nom correspond à un mot connu", "仅部分名称匹配已知词语"],
  "Short, easy to scan label": ["Kort och lättöverskådligt namn", "Nombre corto y fácil de leer", "Nom court et facile à lire", "名称简短，便于浏览"],
  "Long name": ["Långt namn", "Nombre largo", "Nom long", "名称较长"],
  "Hyphens add typing steps": ["Bindestreck kräver extra tecken när du skriver", "Los guiones añaden caracteres al escribir", "Les traits d’union ajoutent des caractères à saisir", "连字符增加输入步骤"],
  "Numbers may make spoken recall harder": ["Siffror kan göra namnet svårare att återge muntligt", "Los números pueden dificultar recordar el nombre al oírlo", "Les chiffres peuvent compliquer la mémorisation à l’oral", "数字可能增加听记难度"],
  "Repeated word": ["Upprepat ord", "Palabra repetida", "Mot répété", "词语重复"],
  "Repeated letters": ["Upprepade bokstäver", "Letras repetidas", "Lettres répétées", "字母重复"],
  "The letter sequence may be hard to pronounce": ["Bokstavsföljden kan vara svår att uttala", "La secuencia de letras puede ser difícil de pronunciar", "La suite de lettres peut être difficile à prononcer", "字母组合可能难以发音"],
  "Resembles a misspelling of a vocabulary word": ["Liknar en felstavning av ett ord i listan", "Se parece a una palabra del vocabulario mal escrita", "Ressemble à une faute d’orthographe d’un mot du vocabulaire", "类似词库中某个词的拼写错误"],
  "A possible coined name needs independent language review": ["Ett möjligt nybildat namn behöver en egen språkgranskning", "Un posible nombre inventado requiere una revisión lingüística independiente", "Un nom potentiellement inventé nécessite une analyse linguistique indépendante", "可能是新造词，需要独立语言核查"],
  ".com receives general commercial weight in this rubric": ["Modellen ger .com en generell kommersiell vikt", "El modelo asigna a .com un peso comercial general", "Le modèle attribue à .com une pondération commerciale générale", "此模型为 .com 赋予一般商业权重"],
  "Swedish words align with .se in this rubric": ["Modellen bedömer att svenska ord passar med .se", "En este modelo, las palabras suecas encajan con .se", "Dans ce modèle, les mots suédois s’accordent avec .se", "此模型认为瑞典语词与 .se 相匹配"],
  "The extension fits the words' application": ["Ändelsen passar ordens användningsområde", "La extensión encaja con el uso de las palabras", "L’extension correspond à l’usage des mots", "后缀与词语用途相符"],
  "The rubric has not established extension fit": ["Modellen har inte kunnat bedöma om ändelsen passar", "El modelo no ha determinado si la extensión encaja", "Le modèle n’a pas établi l’adéquation de l’extension", "模型尚未确定后缀是否适合"],
  "Internationalized name needs separate language review": ["Namn med internationella tecken behöver separat språkgranskning", "Un nombre con caracteres internacionales requiere una revisión lingüística específica", "Un nom avec des caractères internationaux nécessite une analyse linguistique spécifique", "国际化域名需要单独进行语言核查"],
  "This domain format is outside the rubric": ["Modellen stöder inte detta domänformat", "El modelo no admite este formato de dominio", "Le modèle ne prend pas en charge ce format de domaine", "模型不支持此域名格式"],
  "A naming rubric, not measured demand": ["En namnmodell, inte uppmätt efterfrågan", "Un modelo de nombres, no una medición de demanda", "Un modèle de noms, pas une mesure de la demande", "这是名称模型，并非实测需求"],
  "Software or digital service": ["Programvara eller digital tjänst", "Software o servicio digital", "Logiciel ou service numérique", "软件或数字服务"],
  "Financial comparison service": ["Jämförelsetjänst för ekonomi", "Servicio de comparación financiera", "Service de comparaison financière", "金融比较服务"],
  "Housing or property service": ["Bostads- eller fastighetstjänst", "Servicio de vivienda o inmobiliario", "Service de logement ou immobilier", "住房或房地产服务"],
  "Travel or booking service": ["Rese- eller bokningstjänst", "Servicio de viajes o reservas", "Service de voyage ou de réservation", "旅行或预订服务"],
  "Store or e-commerce": ["Butik eller e-handel", "Tienda o comercio electrónico", "Boutique ou commerce en ligne", "商店或电子商务"],
  "Health or wellness service": ["Hälso- eller välmåendetjänst", "Servicio de salud o bienestar", "Service de santé ou de bien-être", "健康或养生服务"],
  "Energy or installation service": ["Energi- eller installationstjänst", "Servicio energético o de instalación", "Service d’énergie ou d’installation", "能源或安装服务"],
  "Education or courses": ["Utbildning eller kurser", "Educación o cursos", "Formation ou cours", "教育或课程"],
  "Business service": ["Företagstjänst", "Servicio para empresas", "Service aux entreprises", "企业服务"],
  "Food or meal service": ["Mat- eller måltidstjänst", "Servicio de alimentación o comidas", "Service alimentaire ou de repas", "食品或餐饮服务"],
  "Creative studio or media project": ["Kreativ studio eller medieprojekt", "Estudio creativo o proyecto de medios", "Studio créatif ou projet média", "创意工作室或媒体项目"],
  "Transport or vehicle service": ["Transport- eller fordonstjänst", "Servicio de transporte o vehículos", "Service de transport ou lié aux véhicules", "交通或车辆服务"],
  "Registry": ["Domänregister", "Registro", "Registre", "注册局"], "DNS": ["DNS", "DNS", "DNS", "DNS"], "Mail": ["E-post", "Correo electrónico", "Messagerie", "电子邮件"],
  "Website": ["Webbplats", "Sitio web", "Site web", "网站"], "Name structure": ["Namnets uppbyggnad", "Estructura del nombre", "Structure du nom", "名称结构"], "Source trail": ["Källspår", "Rastro en las fuentes", "Piste dans les sources", "来源线索"], "Risk deductions": ["Riskavdrag", "Deducciones por riesgo", "Déductions liées aux risques", "风险扣分"],
  "Registrar purchase confirmation": ["Registratorns tillgänglighetsbesked", "Confirmación de disponibilidad del registrador", "Confirmation de disponibilité du bureau d’enregistrement", "注册商的可注册状态确认"],
  "Past use": ["Tidigare användning", "Uso anterior", "Utilisation passée", "历史用途"], "Trademark rights": ["Varumärkesrättigheter", "Derechos de marca", "Droits de marque", "商标权利"], "Comparable sales": ["Jämförbara försäljningar", "Ventas comparables", "Ventes comparables", "可比交易"],
  "Original quote observation time": ["Prisunderlagets ursprungliga kontrolltid", "Fecha original de la comprobación del precio", "Date de la vérification initiale du prix", "原始价格核查时间"],
  "Original technical observations": ["Ursprungliga tekniska observationer", "Observaciones técnicas originales", "Observations techniques initiales", "原始技术观察记录"], "Fresh evidence missing": ["Aktuellt underlag saknas", "Faltan datos recientes", "Données récentes manquantes", "缺少近期证据"], "Valid no later than": ["Giltigt längst till", "Válido como máximo hasta", "Valable au plus tard jusqu’au", "最迟有效至"],
  "Technical deep review": ["Teknisk djupgranskning", "Análisis técnico profundo", "Analyse technique approfondie", "深度技术核查"], "Evidence expired — a fresh check is required": ["Underlaget har löpt ut – ny kontroll krävs", "Los datos han caducado: es necesaria una nueva comprobación", "Données périmées : une nouvelle vérification est nécessaire", "证据已过期，需要重新核查"],
  "Technical gates met for price review": ["Tekniska krav uppfyllda för prisgranskning", "Requisitos técnicos cumplidos para analizar el precio", "Critères techniques remplis pour l’analyse du prix", "已满足价格核查的技术条件"], "Further checks required": ["Fortsatta kontroller krävs", "Se necesitan más comprobaciones", "Vérifications supplémentaires nécessaires", "需要进一步核查"],
  "Excluded from acquisition review": ["Utesluten från förvärvsgranskning", "Excluido del análisis de adquisición", "Exclu de l’analyse d’acquisition", "已排除，不进入收购核查"], "Evidence is incomplete": ["Underlaget är ofullständigt", "Los datos están incompletos", "Données incomplètes", "证据不完整"],
  "This assessment applies at the stated time. Ready for price review does not mean purchasable or undervalued. Four check types are not four independent data providers.": ["Bedömningen gäller vid angiven tid. Klar för prisgranskning betyder inte att domänen går att köpa eller är undervärderad. Fyra kontrolltyper är inte fyra oberoende dataleverantörer.", "La evaluación corresponde al momento indicado. Estar listo para analizar el precio no significa que pueda comprarse ni que esté infravalorado. Cuatro tipos de comprobación no equivalen a cuatro proveedores independientes.", "L’évaluation correspond au moment indiqué. Être prêt pour l’analyse du prix ne signifie pas que le domaine est achetable ou sous-évalué. Quatre types de vérifications ne représentent pas quatre fournisseurs indépendants.", "评估仅适用于标注时刻。可以进行价格核查，不代表域名可购买或被低估。四类核查并不等于四家独立数据提供商。"],
  "A newer check is available. This report must not be used as current purchase evidence; wait for the newer review.": ["En nyare kontroll finns. Använd inte den här rapporten som aktuellt köpunderlag; invänta den nya granskningen.", "Hay una comprobación más reciente. No uses este informe como base actual para comprar; espera al nuevo análisis.", "Une vérification plus récente existe. N’utilisez pas ce rapport comme base d’achat actuelle ; attendez la nouvelle analyse.", "已有更新的核查。请勿将本报告作为当前购买依据，应等待新的核查结果。"],
  "Fresh check types": ["Aktuella kontrolltyper", "Tipos de comprobaciones recientes", "Types de vérifications à jour", "有效的核查类型"], "Consistent checks over time": ["Samstämmiga kontroller över tid", "Comprobaciones coherentes a lo largo del tiempo", "Vérifications concordantes dans le temps", "多次核查结果一致"], "hours (at least 12)": ["timmar (minst 12)", "horas (al menos 12)", "heures (au moins 12)", "小时（至少 12）"], "Assessed": ["Bedömt", "Evaluado", "Évalué", "评估时间"],
  "Review gates and remaining evidence": ["Granskningskrav och återstående underlag", "Requisitos del análisis y datos pendientes", "Critères d’analyse et données manquantes", "核查条件与待补充证据"],
  "Approved source": ["Godkänd källa", "Fuente autorizada", "Source autorisée", "已获准的来源"], "Domain registry": ["Domänregister", "Registro de dominios", "Registre des domaines", "域名注册局"], "DNS addresses": ["DNS-adresser", "Direcciones DNS", "Adresses DNS", "DNS 地址"], "Mail dependencies": ["E-postberoenden", "Dependencias de correo", "Dépendances de messagerie", "邮件依赖"], "Apex domain and web response": ["Huvuddomän och webbsvar", "Dominio raíz y respuesta web", "Domaine racine et réponse web", "根域名与网页响应"],
  "Fresh evidence": ["Aktuellt underlag", "Datos recientes", "Données à jour", "近期证据"], "Stability over time": ["Stabilitet över tid", "Estabilidad en el tiempo", "Stabilité dans le temps", "状态的时间稳定性"], "Archive sample": ["Arkivstickprov", "Muestra de archivo", "Échantillon d’archives", "档案样本"], "Registrability and exact quote": ["Registrerbarhet och exakt pris", "Posibilidad de registro y precio exacto", "Possibilité d’enregistrement et prix exact", "可注册状态与精确报价"],
  "Naming and trademark rights": ["Namn- och varumärkesrättigheter", "Derechos sobre nombres y marcas", "Droits sur les noms et les marques", "名称与商标权利"], "Demand and comparable sales": ["Efterfrågan och jämförbara försäljningar", "Demanda y ventas comparables", "Demande et ventes comparables", "需求与可比交易"],
  "Met": ["Uppfyllt", "Cumplido", "Rempli", "已满足"], "Blocking evidence": ["Hinder upptäckt", "Se ha detectado un impedimento", "Obstacle détecté", "发现阻碍因素"], "Not verified": ["Ej verifierat", "Sin verificar", "Non vérifié", "尚未验证"], "Refresh required": ["Ny kontroll krävs", "Requiere una nueva comprobación", "Nouvelle vérification nécessaire", "需要重新核查"],
  "The registry lifecycle includes a past expiration date or renewal. Neither proves that the domain is available or can be purchased.": ["Registerhistoriken innehåller ett passerat utgångsdatum eller en förnyelse. Det bevisar inte att domänen är ledig eller kan köpas.", "El historial del registro contiene una fecha de vencimiento pasada o una renovación. Ninguna demuestra que el dominio esté disponible o pueda comprarse.", "L’historique du registre contient une date d’expiration passée ou un renouvellement. Cela ne prouve pas que le domaine est disponible ou achetable.", "注册局历史中包含已过的到期日或续费记录。这并不能证明域名可注册或可购买。"],
  "Registrar check": ["Registratorns kontroll", "Comprobación del registrador", "Vérification du bureau d’enregistrement", "注册商核查"], "The registrar reported available at check time": ["Registratorn uppgav att domänen var ledig vid kontrollen", "El registrador indicó que estaba disponible al comprobarlo", "Le bureau d’enregistrement l’a indiqué disponible lors de la vérification", "核查时注册商回复可注册"], "The registrar reported unavailable": ["Registratorn uppgav att domänen inte var ledig", "El registrador indicó que no estaba disponible", "Le bureau d’enregistrement l’a indiqué indisponible", "注册商回复不可注册"],
  "The quote needs refreshing. No current price is displayed.": ["Prisbeskedet behöver förnyas. Inget aktuellt pris visas.", "El precio debe actualizarse. No se muestra un precio vigente.", "Le prix doit être actualisé. Aucun prix actuel n’est affiché.", "报价需要刷新，当前不显示有效价格。"], "No verified registrar response": ["Inget verifierat besked från registratorn", "Sin respuesta verificada del registrador", "Aucune réponse vérifiée du bureau d’enregistrement", "暂无经过验证的注册商回复"],
  "Registration price per year": ["Registreringspris per år", "Precio de registro por año", "Prix d’enregistrement par an", "每年注册价格"], "Not confirmed": ["Ej bekräftat", "Sin confirmar", "Non confirmé", "尚未确认"], "Reported renewal price · term not established": ["Angivet förnyelsepris · perioden är inte fastställd", "Precio de renovación indicado · período sin confirmar", "Prix de renouvellement indiqué · durée non établie", "已报告的续费价格 · 周期尚未确定"],
  "Minimum registration term": ["Minsta registreringsperiod", "Período mínimo de registro", "Durée minimale d’enregistrement", "最短注册期限"], "years": ["år", "años", "ans", "年"], "Registration for the minimum term, before unconfirmed extras": ["Registrering för minsta perioden, före obekräftade tillägg", "Registro por el período mínimo, sin extras aún no confirmados", "Enregistrement pour la durée minimale, hors suppléments non confirmés", "最短期限的注册费用，未含尚未确认的附加费用"],
  "Tax, fees, mandatory add-ons and the renewal contract term are unverified. This is not a final payable total or a reservation.": ["Skatt, avgifter, obligatoriska tillägg och förnyelsens avtalsperiod är inte verifierade. Detta är inte ett slutligt betalbelopp eller en reservation.", "No se han verificado impuestos, comisiones, extras obligatorios ni el período de renovación. No es un importe final de pago ni una reserva.", "Les taxes, frais, options obligatoires et la durée contractuelle du renouvellement ne sont pas vérifiés. Il ne s’agit ni d’un total à payer définitif ni d’une réservation.", "税费、手续费、强制附加项目及续费合约周期均未验证。这不是最终应付总额，也不代表已经预留域名。"],
  "Checked": ["Kontrollerat", "Comprobado", "Vérifié", "核查时间"], "Recheck by": ["Kontrollera igen senast", "Volver a comprobar antes de", "À revérifier au plus tard le", "最迟复查时间"], "Pricing and acquisition evidence": ["Pris- och förvärvsunderlag", "Datos de precio y adquisición", "Données de prix et d’acquisition", "价格与收购依据"],
  "Acquisition evidence expired — recheck before proceeding": ["Förvärvsunderlaget har löpt ut – kontrollera igen innan du går vidare", "Los datos de adquisición han caducado: compruébalos antes de continuar", "Données d’acquisition périmées : revérifiez avant de poursuivre", "收购依据已过期，继续前请重新核查"],
  "Research only — purchase evidence missing": ["Endast för undersökning – köpunderlag saknas", "Solo investigación: faltan datos para una compra", "Recherche uniquement : données d’achat manquantes", "仅供研究，缺少购买依据"], "More evidence needed before a purchase decision": ["Mer underlag krävs före ett köpbeslut", "Se necesitan más datos antes de decidir una compra", "Données supplémentaires nécessaires avant une décision d’achat", "作出购买决定前还需更多证据"], "Evidence ready for your acquisition review": ["Underlaget är klart för din förvärvsgranskning", "Datos listos para tu análisis de adquisición", "Données prêtes pour votre analyse d’acquisition", "证据已备齐，可进行收购核查"],
  "No verified low-price signal. A standard extension price, a good name or an absent registry record is not enough.": ["Ingen verifierad lågprissignal. Ett standardpris för ändelsen, ett bra namn eller ett tomt registersvar räcker inte.", "No hay una señal verificada de precio bajo. Un precio estándar de la extensión, un buen nombre o la ausencia de una entrada en el registro no bastan.", "Aucun signal vérifié de prix bas. Le tarif standard d’une extension, un bon nom ou l’absence d’entrée dans le registre ne suffisent pas.", "没有经过验证的低价信号。后缀的标准价格、好名称或注册局无记录，都不足以得出低价结论。"],
  "The three-year cost scenario is below the reviewed comparison range. This is a research signal, not a promise of a sale price or profit.": ["Den beräknade treårskostnaden ligger under det granskade jämförelseintervallet. Det är en signal att undersöka, inte ett löfte om försäljningspris eller vinst.", "El escenario de coste a tres años está por debajo del intervalo de comparación revisado. Es una señal para investigar, no una promesa de precio de venta ni de beneficio.", "Le scénario de coût sur trois ans est inférieur à la fourchette de comparaison examinée. C’est une piste de recherche, pas une promesse de prix de vente ou de bénéfice.", "三年成本测算低于已核查的比较区间。这是值得调查的信号，并非对售价或利润的保证。"],
  "Scenarios use current price terms; future renewal prices are not locked.": ["Scenarierna använder nuvarande prisvillkor; framtida förnyelsepriser är inte låsta.", "Los escenarios usan las condiciones de precio actuales; los precios de renovación futuros no están fijados.", "Les scénarios utilisent les conditions tarifaires actuelles ; les futurs prix de renouvellement ne sont pas garantis.", "测算使用当前价格条件，不锁定未来续费价格。"],
  "Registrar confirmation for this exact domain": ["Registratorns tillgänglighetsbesked för just denna domän", "Confirmación del registrador para este dominio concreto", "Confirmation du bureau d’enregistrement pour ce domaine précis", "注册商对此域名的明确确认"], "Current quote for this exact domain": ["Aktuellt pris för just denna domän", "Precio actual de este dominio concreto", "Prix actuel de ce domaine précis", "此域名的当前报价"], "Renewal price": ["Förnyelsepris", "Precio de renovación", "Prix de renouvellement", "续费价格"], "All fees": ["Samtliga avgifter", "Todas las comisiones", "Tous les frais", "全部费用"], "Taxes": ["Skatt och moms", "Impuestos", "Taxes", "税费"], "Mandatory add-ons": ["Obligatoriska tillägg", "Extras obligatorios", "Options obligatoires", "强制附加项目"],
  "Reviewed past use": ["Granskad tidigare användning", "Uso anterior revisado", "Utilisation passée examinée", "已核查的历史用途"], "Reviewed naming and trademark risks": ["Granskade namn- och varumärkesrisker", "Riesgos de nombres y marcas revisados", "Risques liés aux noms et aux marques examinés", "已核查的名称与商标风险"], "Sourced comparable sales and a reviewed value range": ["Källbelagda jämförbara försäljningar och granskat värdeintervall", "Ventas comparables con fuentes e intervalo de valor revisado", "Ventes comparables sourcées et fourchette de valeur examinée", "有来源支持的可比交易及经核查的价值区间"],
  "A purchase always requires your confirmation and a fresh registrar check.": ["Ett köp kräver alltid din bekräftelse och en ny kontroll hos registratorn.", "Una compra siempre requiere tu confirmación y una nueva comprobación con el registrador.", "Un achat nécessite toujours votre confirmation et une nouvelle vérification auprès du bureau d’enregistrement.", "购买始终需要你确认，并须向注册商重新核查。"],
  "Name fit": ["Namnmatchning", "Adecuación del nombre", "Pertinence du nom", "名称匹配度"], "Unrated": ["Ej bedömt", "Sin evaluar", "Non évalué", "未评分"],
  "Vocabulary model v1 weighs meaning, application, readability and extension. Its English and Swedish vocabulary is a limited selection; unfamiliar names need independent review. The score is independent of registrability and does not measure demand or market value.": ["Ordmodell v1 väger betydelse, användningsområde, läsbarhet och ändelse. Ordlistan är ett begränsat urval på svenska och engelska; okända namn behöver egen granskning. Poängen är oberoende av registrerbarhet och mäter inte efterfrågan eller marknadsvärde.", "El modelo de vocabulario v1 pondera significado, uso, legibilidad y extensión. Su vocabulario inglés y sueco es limitado; los nombres desconocidos requieren una revisión independiente. La puntuación es independiente de la posibilidad de registro y no mide demanda ni valor de mercado.", "Le modèle de vocabulaire v1 pondère le sens, l’usage, la lisibilité et l’extension. Son vocabulaire anglais et suédois est limité ; les noms inconnus nécessitent une analyse indépendante. Le score est indépendant de la possibilité d’enregistrement et ne mesure ni la demande ni la valeur marchande.", "词汇模型 v1 综合考虑含义、用途、可读性和后缀。其英语和瑞典语词库仅包含有限词汇，未识别的名称需要独立核查。此评分与可注册状态无关，也不衡量需求或市场价值。"],
  "Recognized words": ["Identifierade ord", "Palabras reconocidas", "Mots reconnus", "识别出的词语"], "Meaning · max 40": ["Betydelse · max 40", "Significado · máx. 40", "Sens · max. 40", "含义 · 最高 40"], "Application · max 25": ["Användningsområde · max 25", "Uso · máx. 25", "Usage · max. 25", "用途 · 最高 25"], "Readability · max 20": ["Läsbarhet · max 20", "Legibilidad · máx. 20", "Lisibilité · max. 20", "可读性 · 最高 20"], "Extension · max 15": ["Ändelse · max 15", "Extensión · máx. 15", "Extension · max. 15", "后缀 · 最高 15"], "Name deductions": ["Namnrelaterade avdrag", "Deducciones por el nombre", "Déductions liées au nom", "名称扣分"],
  "Exploratory use cases": ["Användningsidéer att undersöka", "Posibles usos para investigar", "Usages possibles à explorer", "值得探索的用途"], "These ideas come from the words. No buyers or purchase interest have been identified.": ["Idéerna kommer från orden. Inga köpare eller köpintressen har identifierats.", "Las ideas se basan en las palabras. No se han identificado compradores ni interés de compra.", "Ces idées découlent des mots. Aucun acheteur ni intérêt d’achat n’a été identifié.", "这些用途来自词语含义，尚未发现实际买家或购买意向。"],
  "How review priority is calculated": ["Så räknas granskningsprioriteten", "Cómo se calcula la prioridad del análisis", "Comment la priorité d’analyse est calculée", "核查优先级如何计算"],
  "Signal model v1 · not a valuation. A source trail is an observed reference, not verified traffic or backlink authority.": ["Signalmodell v1 · inte en värdering. Källspår betyder en observerad hänvisning, inte verifierad trafik eller länkkraft.", "Modelo de señales v1: no es una valoración. Una pista en las fuentes es una referencia observada, no tráfico ni autoridad de enlaces verificados.", "Modèle de signaux v1 : ce n’est pas une estimation. Une piste dans les sources est une référence observée, pas du trafic ni de l’autorité de liens vérifiés.", "信号模型 v1 并非估值模型。来源线索是观察到的引用，不代表经过验证的流量或外链权重。"],
  "Review priority": ["Granskningsprioritet", "Prioridad del análisis", "Priorité d’analyse", "核查优先级"], "Still needed before a purchase decision": ["Återstår före ett köpbeslut", "Pendiente antes de decidir una compra", "Éléments manquants avant une décision d’achat", "购买决定前仍需补充"],
  "Public archive sample": ["Stickprov från publikt arkiv", "Muestra de archivo público", "Échantillon d’archives publiques", "公开档案样本"],
  "At most 5 metadata observations from 1 collection. Dates describe this sample, not the domain's first or last use ever. This evidence does not establish ownership, traffic, backlink quality or trademark rights.": ["Högst 5 metadataobservationer från 1 insamling. Datumen gäller bara stickprovet, inte domänens första eller senaste användning någonsin. Underlaget visar inte ägare, trafik, länkkvalitet eller varumärkesrättigheter.", "Como máximo 5 observaciones de metadatos de 1 colección. Las fechas describen esta muestra, no el primer o último uso del dominio. Los datos no demuestran propiedad, tráfico, calidad de enlaces ni derechos de marca.", "Au maximum 5 observations de métadonnées d’une seule collecte. Les dates décrivent cet échantillon, pas la première ou la dernière utilisation du domaine. Ces données n’établissent ni propriété, ni trafic, ni qualité des liens, ni droits de marque.", "最多从 1 次采集中提取 5 条元数据观察记录。日期仅对应此样本，不代表域名有史以来最早或最近的使用时间。这些数据不能证明所有权、流量、外链质量或商标权利。"],
  "The domain appears in archive metadata.": ["Domänen förekommer i arkivets metadata.", "El dominio aparece en los metadatos del archivo.", "Le domaine apparaît dans les métadonnées des archives.", "档案元数据中出现了此域名。"], "Archive checks are not enabled.": ["Arkivkontroll är inte aktiverad.", "La comprobación de archivos no está activada.", "La vérification des archives n’est pas activée.", "档案核查尚未启用。"],
  "No sample was found in the checked collection.": ["Inget stickprov hittades i den kontrollerade insamlingen.", "No se encontró ninguna muestra en la colección consultada.", "Aucun échantillon trouvé dans la collecte vérifiée.", "在所查采集中未找到样本。"], "The archive check did not return reliable evidence.": ["Arkivkontrollen gav inget tillförlitligt underlag.", "La comprobación del archivo no devolvió datos fiables.", "La vérification des archives n’a pas fourni de données fiables.", "档案核查未返回可靠证据。"], "Missing archive data does not prove that the domain has no history.": ["Avsaknad av arkivdata bevisar inte att domänen saknar historik.", "La falta de datos de archivo no demuestra que el dominio carezca de historial.", "L’absence de données d’archives ne prouve pas que le domaine n’a pas d’historique.", "缺少档案数据并不能证明域名没有历史。"],
  "Collection": ["Insamling", "Colección", "Collecte", "采集批次"], "Metadata samples": ["Metadata i stickprovet", "Muestras de metadatos", "Échantillons de métadonnées", "元数据样本"], "HTTP statuses in the sample": ["HTTP-statusar i stickprovet", "Estados HTTP de la muestra", "Statuts HTTP de l’échantillon", "样本中的 HTTP 状态"], "Earliest in the sample": ["Tidigast i stickprovet", "Fecha más antigua de la muestra", "Date la plus ancienne de l’échantillon", "样本最早时间"], "Latest in the sample": ["Senast i stickprovet", "Fecha más reciente de la muestra", "Date la plus récente de l’échantillon", "样本最近时间"],
  "Open the metadata query at Common Crawl": ["Öppna metadatafrågan hos Common Crawl", "Abrir la consulta de metadatos en Common Crawl", "Ouvrir la requête de métadonnées sur Common Crawl", "在 Common Crawl 中打开元数据查询"], "Sajda observation history": ["Sajdas observationshistorik", "Historial de observaciones de Sajda", "Historique des observations Sajda", "Sajda 观察历史"],
  "Your account's checks over the last 180 days. This is not the domain's ownership or traffic history.": ["Ditt kontos kontroller under de senaste 180 dagarna. Detta är inte domänens ägar- eller trafikhistorik.", "Las comprobaciones de tu cuenta durante los últimos 180 días. No es el historial de propiedad ni de tráfico del dominio.", "Les vérifications de votre compte sur les 180 derniers jours. Ce n’est pas l’historique des propriétaires ni du trafic du domaine.", "展示你账户过去 180 天的核查记录，并非域名所有权或流量历史。"],
  "First seen in this window": ["Först observerad under perioden", "Primera observación del período", "Première observation sur cette période", "此期间首次观察时间"], "Checks / distinct source domains": ["Kontroller / olika källdomäner", "Comprobaciones / dominios de origen distintos", "Vérifications / domaines sources distincts", "核查次数 / 不同来源域名数"], "Registry status changed since the previous check.": ["Registerstatus har ändrats sedan föregående kontroll.", "El estado del registro ha cambiado desde la comprobación anterior.", "Le statut dans le registre a changé depuis la vérification précédente.", "注册局状态自上次核查后已变化。"],
  "Trading workspace": ["Trading-arbetsyta", "Espacio Trading", "Espace Trading", "Trading 工作区"], "approved source pages available now.": ["godkända källsidor tillgängliga just nu.", "páginas de origen autorizadas disponibles ahora.", "pages sources autorisées disponibles actuellement.", "个已获准的来源页面当前可用。"],
  "Rechecking the highest-priority candidates with fresh registry and risk observations.": ["Kontrollerar de högst prioriterade kandidaterna igen med nya register- och riskobservationer.", "Volviendo a comprobar los candidatos prioritarios con nuevas observaciones del registro y de riesgos.", "Nouvelle vérification des candidats prioritaires avec des observations actualisées du registre et des risques.", "正在用新的注册局与风险观察记录复查最高优先级候选。"],
  "Final rechecks": ["Slutkontroller", "Comprobaciones finales", "Vérifications finales", "最终复查"], "Domains in this report": ["Domäner i rapporten", "Dominios del informe", "Domaines dans ce rapport", "报告中的域名"], "Strong current signals": ["Starka aktuella signaler", "Señales actuales sólidas", "Signaux actuels solides", "当前强信号"], "Strong name fit": ["Stark namnmatchning", "Alta adecuación del nombre", "Forte pertinence du nom", "名称匹配度高"], "Registry changes": ["Ändringar i registret", "Cambios en el registro", "Changements du registre", "注册局变化"], "Approved source pages": ["Godkända källsidor", "Páginas de origen autorizadas", "Pages sources autorisées", "已获准的来源页面"],
  "Filter domain": ["Filtrera domäner", "Filtrar dominios", "Filtrer les domaines", "筛选域名"], "Search this report…": ["Sök i rapporten…", "Buscar en este informe…", "Rechercher dans ce rapport…", "搜索此报告…"], "Status": ["Status", "Estado", "Statut", "状态"],
  "All checks": ["Alla kontroller", "Todas las comprobaciones", "Toutes les vérifications", "全部核查"], "Ready for price review": ["Klara för prisgranskning", "Listos para analizar el precio", "Prêts pour l’analyse du prix", "可以进行价格核查"], "Acquisition evidence complete": ["Komplett förvärvsunderlag", "Datos de adquisición completos", "Données d’acquisition complètes", "收购依据完整"], "Strong technical signals": ["Starka tekniska signaler", "Señales técnicas sólidas", "Signaux techniques solides", "技术信号强"], "Registry changed": ["Ändrad registerstatus", "Estado del registro modificado", "Statut du registre modifié", "注册局状态已变化"], "Registry absent": ["Saknas i registersvaret", "Ausente de la respuesta del registro", "Absent de la réponse du registre", "注册局回复中无记录"], "Registered": ["Registrerade", "Registrados", "Enregistrés", "已注册"], "Unknown status": ["Okänd status", "Estado desconocido", "Statut inconnu", "状态未知"], "Excluded": ["Uteslutna", "Excluidos", "Exclus", "已排除"],
  "Extension": ["Ändelse", "Extensión", "Extension", "后缀"], "All extensions": ["Alla ändelser", "Todas las extensiones", "Toutes les extensions", "所有后缀"], "Export CSV": ["Exportera CSV", "Exportar CSV", "Exporter en CSV", "导出 CSV"],
  "checks match this selection. Export includes observation time and unverified registrability.": ["kontroller matchar urvalet. Exporten innehåller observationstid och uppgift om att registrerbarheten inte är verifierad.", "comprobaciones coinciden con la selección. La exportación incluye la fecha de observación e indica que la posibilidad de registro no está verificada.", "vérifications correspondent à la sélection. L’export inclut l’heure d’observation et indique que la possibilité d’enregistrement n’est pas vérifiée.", "条核查符合筛选条件。导出包含观察时间，并标明可注册状态尚未验证。"],
  "Strong name fit describes the words and extension. Check registry status separately; this filter can also include registered domains.": ["Stark namnmatchning beskriver orden och ändelsen. Kontrollera registerstatus separat; filtret kan även visa registrerade domäner.", "La alta adecuación del nombre describe las palabras y la extensión. Comprueba el estado del registro por separado; el filtro también puede incluir dominios registrados.", "La forte pertinence du nom décrit les mots et l’extension. Vérifiez séparément le statut du registre ; ce filtre peut aussi afficher des domaines enregistrés.", "名称匹配度高仅描述词语与后缀的适合程度。请单独核查注册局状态，此筛选也可能包含已注册域名。"],
  "Export could not be created. Your report is preserved. Try again.": ["Exporten kunde inte skapas. Rapporten är kvar. Försök igen.", "No se pudo crear la exportación. Tu informe se conserva. Inténtalo de nuevo.", "Impossible de créer l’export. Votre rapport est conservé. Réessayez.", "无法生成导出文件。报告仍保留，请重试。"],
  "Registrar responses are timestamped observations. Sajda has not reserved or purchased any domain.": ["Registratorsvar är tidsbundna observationer. Sajda har inte reserverat eller köpt någon domän.", "Las respuestas del registrador son observaciones con fecha y hora. Sajda no ha reservado ni comprado ningún dominio.", "Les réponses du bureau d’enregistrement sont des observations horodatées. Sajda n’a réservé ni acheté aucun domaine.", "注册商回复是带时间戳的观察记录。Sajda 未预留或购买任何域名。"],
  "other checks displayed. Search and CSV include all matching rows in this report.": ["övriga kontroller visas. Sökning och CSV omfattar alla matchande rader i rapportunderlaget.", "comprobaciones adicionales mostradas. La búsqueda y el CSV incluyen todas las filas del informe que coinciden.", "autres vérifications affichées. La recherche et le CSV incluent toutes les lignes correspondantes du rapport.", "条其他核查已显示。搜索和 CSV 包含报告中所有符合条件的行。"],
  "Account and Trading subscription": ["Konto och Trading-abonnemang", "Cuenta y suscripción Trading", "Compte et abonnement Trading", "账户与 Trading 订阅"], "Consistent rounds": ["Samstämmiga omgångar", "Rondas coherentes", "Séries concordantes", "结果一致的轮次"], "Technically ready for price review — not a purchase confirmation": ["Tekniskt klar för prisgranskning – inte ett köpbesked", "Técnicamente listo para analizar el precio: no confirma una compra", "Techniquement prêt pour l’analyse du prix : aucune confirmation d’achat", "技术上已可进行价格核查，但不代表购买确认"], "More checks required": ["Fler kontroller krävs", "Se necesitan más comprobaciones", "Vérifications supplémentaires nécessaires", "还需更多核查"], "Evidence is missing": ["Underlag saknas", "Faltan datos", "Données manquantes", "缺少证据"],
} satisfies Record<string, readonly [string, string, string, string]>;

export type TradingPhrase = keyof typeof tradingPhrases;
export function tradingText(language: string, english: TradingPhrase): string {
  const indices: Partial<Record<string, number>> = { sv: 0, es: 1, fr: 2, zh: 3 };
  const index = indices[language];
  return index === undefined ? english : tradingPhrases[english][index];
}

export const tradingLocale: Record<Language, string> = { en: "en-US", sv: "sv-SE", es: "es-ES", fr: "fr-FR", zh: "zh-CN" };

export function tradingRunCapacity(language: string, sources: number, names: number, rounds: number): string {
  if (language === "sv") return `Den här körningen: högst ${sources} källsidor och ${names} namn. Upp till 30 prioriterade namn kontrolleras igen i ${rounds} omgångar.`;
  if (language === "es") return `Esta ejecución: hasta ${sources} páginas de origen y ${names} nombres. Hasta 30 nombres prioritarios se vuelven a comprobar en ${rounds} rondas.`;
  if (language === "fr") return `Cette exécution : jusqu’à ${sources} pages sources et ${names} noms. Jusqu’à 30 noms prioritaires sont revérifiés en ${rounds} séries.`;
  if (language === "zh") return `本次运行最多检查 ${sources} 个来源页面和 ${names} 个名称。其中最多 30 个优先名称接受 ${rounds} 轮复查。`;
  return `This run: up to ${sources} source pages and ${names} names. Up to 30 priority names are rechecked in ${rounds} rounds.`;
}

export function tradingOmittedRows(language: string, count: number): string {
  if (language === "sv") return `Rapporten är stor. Antal utelämnade kontrollrader: ${count}. Sökning och CSV omfattar endast det hämtade underlaget.`;
  if (language === "es") return `El informe es grande. Filas de comprobación omitidas: ${count}. La búsqueda y el CSV solo incluyen los datos recibidos.`;
  if (language === "fr") return `Le rapport est volumineux. Lignes de vérification omises : ${count}. La recherche et le CSV incluent uniquement les données reçues.`;
  if (language === "zh") return `报告较大，已省略 ${count} 条核查行。搜索与 CSV 仅包含已加载的数据。`;
  return `This report is large. Check rows omitted: ${count}. Search and CSV include only the returned data.`;
}

export function tradingShowMore(language: string, count: number): string {
  if (language === "sv") return `Visa ${count} till`;
  if (language === "es") return `Mostrar ${count} más`;
  if (language === "fr") return `Afficher ${count} de plus`;
  if (language === "zh") return `再显示 ${count} 条`;
  return `Show ${count} more`;
}
