import { useEffect, useMemo, useState } from "react";
import { ArrowUpRight, Check, Copy, Download, ExternalLink, FileCode2, Link2, ShieldCheck } from "lucide-react";
import { useLanguage, type Language } from "@/i18n/LanguageProvider";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

export interface SaleLandingGeneratorProps {
  /** The exact domain being offered for sale, for example `example.com`. */
  domain: string;
  /** A seller-set price. Numeric values are formatted for the selected UI language. */
  price: number | string;
  /** An ISO currency code such as `USD`, `EUR`, or `SEK`. */
  currency: string;
  /** A concise, buyer-facing description of the domain. */
  description?: string;
  /** The direct, public URL of the Sajda listing. `http`, `https`, and relative links are supported. */
  listingUrl: string;
  /**
   * Optional validated contact or offer route. It is never rendered unless it
   * is an explicit HTTP(S) URL, so a generated page cannot accidentally claim
   * it handles an offer, payment, or ownership transfer itself.
   */
  contactUrl?: string;
  className?: string;
}

type SaleLandingCopy = {
  eyebrow: string;
  title: string;
  body: string;
  ready: string;
  preview: string;
  previewNote: string;
  price: string;
  viewListing: string;
  listingLink: string;
  publicListingUrl: string;
  publicListingHint: string;
  validLink: string;
  invalidLink: string;
  localLink: string;
  localLinkHint: string;
  contactLink: string;
  contactReady: string;
  contactMissing: string;
  disclosure: string;
  download: string;
  downloadHint: string;
  downloaded: string;
  copied: string;
  copyLink: string;
  deployTitle: string;
  deployBody: string;
  deployStepOne: string;
  deployStepTwo: string;
  deployStepThree: string;
  defaultDescription: string;
  priceOnRequest: string;
  documentEyebrow: string;
  documentAvailable: string;
  documentProfile: string;
  documentRoute: string;
  documentOffer: string;
  documentNoOffer: string;
  documentDirect: string;
  documentPowered: string;
  documentDisclosure: string;
};

const saleLandingCopy: Record<Language, SaleLandingCopy> = {
  en: {
    eyebrow: "For-sale page",
    title: "Create a page for your domain.",
    body: "Create a simple, polished page for a domain you are selling. Download one HTML file and publish it on the hosting service your domain uses.",
    ready: "Standalone HTML",
    preview: "Preview for buyers",
    previewNote: "The buyer button goes straight to this Sajda listing.",
    price: "Asking price",
    viewListing: "View listing on Sajda",
    listingLink: "Direct listing link",
    publicListingUrl: "Public Sajda listing URL",
    publicListingHint: "Use the public Sajda address that a buyer can open from any device.",
    validLink: "Listing link ready",
    invalidLink: "Add a valid listing link to enable the buyer button.",
    localLink: "A public listing URL is needed",
    localLinkHint: "This link only works on your device. Replace it with the public Sajda listing URL before exporting.",
    contactLink: "Inquiry link",
    contactReady: "A separate inquiry link will be included.",
    contactMissing: "No separate inquiry link has been added. Buyers can use the Sajda listing.",
    disclosure: "This is a simple page generated by Sajda. Availability, final price, and any transaction are confirmed on the linked listing.",
    download: "Download index.html",
    downloadHint: "One file. No scripts, credentials, trackers, or hosting connection included.",
    downloaded: "Your standalone page is ready to download.",
    copied: "Link copied",
    copyLink: "Copy listing link",
    deployTitle: "Publish in three steps",
    deployBody: "Use it as the home page for a parked domain, or publish it with any static host.",
    deployStepOne: "Download the single index.html file.",
    deployStepTwo: "Upload it to the domain or static host you control.",
    deployStepThree: "Keep the Sajda listing link current.",
    defaultDescription: "A distinctive domain name, offered through Sajda.",
    priceOnRequest: "Price on request",
    documentEyebrow: "Domain for sale",
    documentAvailable: "This domain is offered through Sajda.",
    documentProfile: "Domain profile",
    documentRoute: "Go directly to the listing",
    documentOffer: "Make an inquiry",
    documentNoOffer: "Details are available on the Sajda listing.",
    documentDirect: "View on Sajda",
    documentPowered: "Listed with Sajda",
    documentDisclosure: "This page is a lightweight sales page generated by Sajda. Availability, final price, and any transaction are confirmed on the linked listing.",
  },
  sv: {
    eyebrow: "Säljsida",
    title: "Skapa en sida för din domän.",
    body: "Skapa en enkel, välgjord sida för en domän du säljer. Ladda ner en HTML-fil och publicera den på webbhotellet som domänen använder.",
    ready: "Fristående HTML",
    preview: "Förhandsvisning för köpare",
    previewNote: "Köparknappen leder direkt till annonsen på Sajda.",
    price: "Begärt pris",
    viewListing: "Visa annonsen på Sajda",
    listingLink: "Direktlänk till annonsen",
    publicListingUrl: "Publik Sajda-länk till annonsen",
    publicListingHint: "Använd den publika Sajda-adress som en köpare kan öppna från valfri enhet.",
    validLink: "Annonslänken är klar",
    invalidLink: "Lägg till en giltig annonslänk för att aktivera köparknappen.",
    localLink: "En publik annonslänk behövs",
    localLinkHint: "Den här länken fungerar bara på din enhet. Ersätt den med den publika Sajda-länken före export.",
    contactLink: "Kontaktväg",
    contactReady: "En separat kontaktlänk följer med sidan.",
    contactMissing: "Ingen separat kontaktlänk har lagts till. Köpare kan använda Sajda-annonsen.",
    disclosure: "Det här är en enkel sida skapad av Sajda. Tillgänglighet, slutpris och eventuell affär bekräftas på den länkade annonsen.",
    download: "Ladda ner index.html",
    downloadHint: "En fil. Inga skript, inloggningsuppgifter, spårningsverktyg eller anslutning till ett webbhotell ingår.",
    downloaded: "Din fristående sida är redo att laddas ner.",
    copied: "Länken är kopierad",
    copyLink: "Kopiera annonslänk",
    deployTitle: "Publicera i tre steg",
    deployBody: "Använd sidan som startsida för en parkerad domän eller publicera den hos en tjänst för statiska webbsidor.",
    deployStepOne: "Ladda ner den enda filen, index.html.",
    deployStepTwo: "Ladda upp filen till webbhotellet eller den tjänst för statiska webbsidor som du använder.",
    deployStepThree: "Håll Sajda-annonsens länk uppdaterad.",
    defaultDescription: "Ett särskiljande domännamn som erbjuds via Sajda.",
    priceOnRequest: "Pris på begäran",
    documentEyebrow: "Domän till salu",
    documentAvailable: "Den här domänen erbjuds via Sajda.",
    documentProfile: "Domänprofil",
    documentRoute: "Gå direkt till annonsen",
    documentOffer: "Gör en förfrågan",
    documentNoOffer: "Detaljer finns i Sajda-annonsen.",
    documentDirect: "Visa på Sajda",
    documentPowered: "Annons på Sajda",
    documentDisclosure: "Den här sidan är en enkel försäljningssida skapad av Sajda. Tillgänglighet, slutpris och eventuell affär bekräftas på den länkade annonsen.",
  },
  es: {
    eyebrow: "Página de venta",
    title: "Crea una página para tu dominio.",
    body: "Crea una página sencilla y cuidada para un dominio que vendes. Descarga un archivo HTML y publícalo en el alojamiento que usa tu dominio.",
    ready: "HTML independiente",
    preview: "Vista previa para compradores",
    previewNote: "El botón lleva directamente al anuncio de Sajda.",
    price: "Precio solicitado",
    viewListing: "Ver anuncio en Sajda",
    listingLink: "Enlace directo al anuncio",
    publicListingUrl: "URL pública del anuncio de Sajda",
    publicListingHint: "Usa la dirección pública de Sajda que un comprador pueda abrir desde cualquier dispositivo.",
    validLink: "Enlace del anuncio listo",
    invalidLink: "Añade un enlace válido al anuncio para activar el botón que lleva a él.",
    localLink: "Se necesita una URL pública del anuncio",
    localLinkHint: "Este enlace solo funciona en tu dispositivo. Sustitúyelo por la URL pública de Sajda antes de exportar.",
    contactLink: "Enlace de consulta",
    contactReady: "Se incluirá un enlace de consulta independiente.",
    contactMissing: "No se ha añadido un enlace de consulta independiente. Los compradores pueden usar el anuncio de Sajda.",
    disclosure: "Esta es una página sencilla generada por Sajda. La disponibilidad, el precio final y cualquier transacción se confirman en el anuncio enlazado.",
    download: "Descargar index.html",
    downloadHint: "Un archivo. No incluye scripts, credenciales, rastreadores ni conexión a un servicio de alojamiento.",
    downloaded: "Tu página independiente está lista para descargar.",
    copied: "Enlace copiado",
    copyLink: "Copiar enlace del anuncio",
    deployTitle: "Publícala en tres pasos sencillos",
    deployBody: "Úsala como página de inicio de un dominio aparcado o publícala en cualquier alojamiento estático.",
    deployStepOne: "Descarga el único archivo index.html.",
    deployStepTwo: "Súbelo al dominio o alojamiento estático que controlas.",
    deployStepThree: "Mantén actualizado el enlace del anuncio de Sajda.",
    defaultDescription: "Un nombre de dominio distintivo ofrecido a través de Sajda.",
    priceOnRequest: "Precio a consultar",
    documentEyebrow: "Dominio en venta",
    documentAvailable: "Este dominio se ofrece a través de Sajda.",
    documentProfile: "Perfil del dominio",
    documentRoute: "Ir directamente al anuncio",
    documentOffer: "Hacer una consulta",
    documentNoOffer: "Los detalles están disponibles en el anuncio de Sajda.",
    documentDirect: "Ver en Sajda",
    documentPowered: "Anuncio en Sajda",
    documentDisclosure: "Esta página es una página de venta ligera generada por Sajda. La disponibilidad, el precio final y cualquier transacción se confirman en el anuncio enlazado.",
  },
  fr: {
    eyebrow: "Page de vente",
    title: "Créez une page pour votre domaine.",
    body: "Créez une page simple et soignée pour un domaine à vendre. Téléchargez un fichier HTML et publiez-le sur l’hébergement utilisé par votre domaine.",
    ready: "HTML autonome",
    preview: "Aperçu pour l’acheteur",
    previewNote: "Le bouton mène directement à l’annonce Sajda.",
    price: "Prix demandé",
    viewListing: "Voir l’annonce sur Sajda",
    listingLink: "Lien direct vers l’annonce",
    publicListingUrl: "URL publique de l’annonce Sajda",
    publicListingHint: "Utilisez l’adresse Sajda publique qu’un acheteur peut ouvrir depuis n’importe quel appareil.",
    validLink: "Lien de l’annonce prêt",
    invalidLink: "Ajoutez un lien d’annonce valide pour activer le bouton acheteur.",
    localLink: "Une URL publique est nécessaire",
    localLinkHint: "Ce lien ne fonctionne que sur votre appareil. Remplacez-le par l’URL Sajda publique avant l’export.",
    contactLink: "Lien de contact",
    contactReady: "Un lien de contact distinct sera inclus.",
    contactMissing: "Aucun lien de contact distinct n’a été ajouté. Les acheteurs peuvent utiliser l’annonce Sajda.",
    disclosure: "Cette page simple est générée par Sajda. La disponibilité, le prix final et toute transaction sont confirmés sur l’annonce liée.",
    download: "Télécharger index.html",
    downloadHint: "Un fichier. Aucun script, identifiant, traceur ni connexion à un hébergement n’est inclus.",
    downloaded: "Votre page autonome est prête à être téléchargée.",
    copied: "Lien copié",
    copyLink: "Copier le lien de l’annonce",
    deployTitle: "Publiez-la en trois étapes simples",
    deployBody: "Utilisez-la comme page d’accueil pour un domaine parqué ou publiez-la chez n’importe quel hébergeur statique.",
    deployStepOne: "Téléchargez l’unique fichier index.html.",
    deployStepTwo: "Importez-le sur le domaine ou l’hébergement statique que vous contrôlez.",
    deployStepThree: "Gardez à jour le lien de l’annonce Sajda.",
    defaultDescription: "Un nom de domaine distinctif proposé via Sajda.",
    priceOnRequest: "Prix sur demande",
    documentEyebrow: "Domaine à vendre",
    documentAvailable: "Ce domaine est proposé via Sajda.",
    documentProfile: "Profil du domaine",
    documentRoute: "Accéder directement à l’annonce",
    documentOffer: "Faire une demande",
    documentNoOffer: "Les détails sont disponibles sur l’annonce Sajda.",
    documentDirect: "Voir sur Sajda",
    documentPowered: "Annonce Sajda",
    documentDisclosure: "Cette page est une page de vente légère générée par Sajda. La disponibilité, le prix final et toute transaction sont confirmés sur l’annonce liée.",
  },
  zh: {
    eyebrow: "出售页面",
    title: "为你的域名创建出售页面。",
    body: "为待售域名制作一个简洁、专业的页面。下载一个 HTML 文件，再发布到域名使用的托管服务。",
    ready: "独立 HTML",
    preview: "买家预览",
    previewNote: "买家按钮会直接跳转至 Sajda 挂牌。",
    price: "挂牌价格",
    viewListing: "在 Sajda 查看挂牌",
    listingLink: "挂牌直达链接",
    publicListingUrl: "公开 Sajda 挂牌 URL",
    publicListingHint: "使用买家可从任意设备打开的公开 Sajda 地址。",
    validLink: "挂牌链接已就绪",
    invalidLink: "请添加有效的挂牌链接以启用买家按钮。",
    localLink: "需要公开挂牌 URL",
    localLinkHint: "此链接仅在你的设备上有效。导出前请将其替换为公开 Sajda 挂牌 URL。",
    contactLink: "咨询链接",
    contactReady: "页面将包含单独的咨询链接。",
    contactMissing: "尚未添加单独的咨询链接，买家可以使用 Sajda 挂牌页面。",
    disclosure: "这是由 Sajda 生成的简洁页面。可用性、最终价格和任何交易均以链接中的挂牌信息为准。",
    download: "下载 index.html",
    downloadHint: "仅一个文件，不含脚本、登录凭据、跟踪工具，也不会连接托管服务。",
    downloaded: "你的独立页面已准备好下载。",
    copied: "链接已复制",
    copyLink: "复制挂牌链接",
    deployTitle: "三步即可发布",
    deployBody: "可将其作为停放域名的首页，或发布到任何静态托管服务。",
    deployStepOne: "下载唯一的 index.html 文件。",
    deployStepTwo: "上传至你控制的域名或静态托管服务。",
    deployStepThree: "保持 Sajda 挂牌链接为最新状态。",
    defaultDescription: "一个通过 Sajda 出售的独特域名。",
    priceOnRequest: "价格面议",
    documentEyebrow: "域名出售中",
    documentAvailable: "该域名通过 Sajda 提供。",
    documentProfile: "域名资料",
    documentRoute: "直达挂牌页面",
    documentOffer: "发送咨询",
    documentNoOffer: "详情请查看 Sajda 挂牌。",
    documentDirect: "在 Sajda 查看",
    documentPowered: "Sajda 挂牌",
    documentDisclosure: "此页面是 Sajda 生成的轻量销售页面。可用性、最终价格和任何交易均以链接中的挂牌信息为准。",
  },
};

const localeByLanguage: Record<Language, string> = {
  en: "en-US",
  sv: "sv-SE",
  es: "es-ES",
  fr: "fr-FR",
  zh: "zh-CN",
};

/** Escapes dynamic content before it is inserted into the downloadable HTML document. */
// Exported for standalone sale-page validation; it is deliberately not a React component.
// eslint-disable-next-line react-refresh/only-export-components
export function escapeSaleLandingHtml(value: string | number) {
  return String(value)
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;")
    .replace(/'/g, "&#39;");
}

/**
 * A downloadable page is deliberately limited to normal web destinations.
 * It cannot download, open a mail client, execute a script, or carry a
 * pseudo-checkout URL. Keeping the route explicit also makes every CTA
 * inspectable in the generated one-file page.
 */
function safeOutboundUrl(value?: string) {
  const candidate = value?.trim() ?? "";
  const hasControlCharacter = [...candidate].some((character) => {
    const code = character.charCodeAt(0);
    return code <= 31 || code === 127;
  });
  if (!candidate || hasControlCharacter) return null;

  try {
    const parsed = new URL(candidate);
    return parsed.protocol === "https:" || parsed.protocol === "http:" ? parsed.href : null;
  } catch {
    return null;
  }
}

function isLocalDevelopmentUrl(value: string | null) {
  if (!value) return false;

  try {
    const hostname = new URL(value).hostname.toLowerCase().replace(/^\[|\]$/g, "");
    return hostname === "localhost" || hostname === "::1" || hostname.startsWith("127.");
  } catch {
    return false;
  }
}

function formatListingPrice(price: number | string, currency: string, language: Language, priceOnRequest: string) {
  const normalizedCurrency = currency.trim().toUpperCase();
  if (typeof price === "number" && Number.isFinite(price)) {
    if (normalizedCurrency) {
      try {
        return new Intl.NumberFormat(localeByLanguage[language], {
          style: "currency",
          currency: normalizedCurrency,
          maximumFractionDigits: Number.isInteger(price) ? 0 : 2,
        }).format(price);
      } catch {
        return `${price.toLocaleString(localeByLanguage[language])} ${normalizedCurrency}`;
      }
    }

    return price.toLocaleString(localeByLanguage[language]);
  }

  const textPrice = String(price).trim();
  return textPrice ? [textPrice, normalizedCurrency].filter(Boolean).join(" ") : priceOnRequest;
}

function displayDomain(domain: string) {
  return domain.trim() || "yourdomain.com";
}

type SaleLandingDocumentOptions = {
  domain: string;
  price: string;
  description: string;
  listingUrl: string | null;
  contactUrl: string | null;
  language: Language;
};

/**
 * Produces a complete network-free sales page. It uses no remote fonts,
 * images, scripts, tracking, embeds, or runtime dependencies. Dynamic text
 * and outbound hrefs are escaped before interpolation; invalid URLs do not
 * receive a CTA.
 */
// Exported so generated sale pages can be verified independently of the UI.
// eslint-disable-next-line react-refresh/only-export-components
export function createSaleLandingHtml({
  domain,
  price,
  description,
  listingUrl,
  contactUrl,
  language,
}: SaleLandingDocumentOptions) {
  const strings = saleLandingCopy[language];
  const deployableListingUrl = listingUrl && !isLocalDevelopmentUrl(listingUrl) ? listingUrl : null;
  const deployableContactUrl = contactUrl && !isLocalDevelopmentUrl(contactUrl) ? contactUrl : null;
  const escapedDomain = escapeSaleLandingHtml(domain);
  const escapedPrice = escapeSaleLandingHtml(price);
  const escapedDescription = escapeSaleLandingHtml(description).replace(/\r?\n/g, "<br>");
  const listingButton = deployableListingUrl
    ? `<a class="button button-primary" href="${escapeSaleLandingHtml(deployableListingUrl)}" target="_blank" rel="noopener noreferrer">${escapeSaleLandingHtml(strings.documentDirect)} <span aria-hidden="true">↗</span></a>`
    : "";
  const contactButton = deployableContactUrl
    ? `<a class="button button-secondary" href="${escapeSaleLandingHtml(deployableContactUrl)}" target="_blank" rel="noopener noreferrer">${escapeSaleLandingHtml(strings.documentOffer)} <span aria-hidden="true">↗</span></a>`
    : "";
  const routeNote = deployableContactUrl ? strings.documentRoute : strings.documentNoOffer;
  const documentLanguage = escapeSaleLandingHtml(language);
  const documentDescription = escapeSaleLandingHtml(description.replace(/\s+/g, " ").trim().slice(0, 180));

  return `<!doctype html>
<html lang="${documentLanguage}">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="color-scheme" content="light">
  <meta name="description" content="${documentDescription}">
  <title>${escapedDomain} — ${escapeSaleLandingHtml(strings.documentEyebrow)} | Sajda</title>
  <style>
    :root { color-scheme: light; --ink: #13213a; --muted: #66758d; --line: #dce6f2; --paper: #ffffff; --canvas: #f4f7fb; --blue: #176fe6; --blue-deep: #115bbf; --blue-soft: #eef6ff; --cyan: #21b5d8; }
    * { box-sizing: border-box; }
    html { background: var(--canvas); }
    body { min-width: 320px; margin: 0; background: radial-gradient(circle at 86% 7%, rgba(33, 181, 216, .1), transparent 26rem), var(--canvas); color: var(--ink); font-family: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; }
    a { color: inherit; }
    .shell { width: min(100% - 32px, 1040px); margin: 0 auto; padding: 28px 0 48px; }
    .topbar { display: flex; align-items: center; justify-content: space-between; gap: 18px; }
    .brand { display: inline-flex; align-items: center; gap: 11px; color: var(--ink); text-decoration: none; font-size: 20px; font-weight: 780; letter-spacing: -.04em; }
    .mark { display: grid; width: 34px; height: 34px; place-items: center; border-radius: 11px; color: #fff; background: linear-gradient(135deg, #25a2f1, #1557ce 72%); box-shadow: 0 9px 20px rgba(22, 111, 230, .22); font-size: 20px; font-style: italic; }
    .listing-state { display: inline-flex; align-items: center; gap: 8px; color: var(--muted); font-size: 12px; font-weight: 700; letter-spacing: .09em; text-transform: uppercase; }
    .listing-state::before { width: 7px; height: 7px; border-radius: 999px; background: #2bb673; box-shadow: 0 0 0 4px rgba(43, 182, 115, .12); content: ""; }
    main { margin-top: clamp(48px, 9vw, 96px); }
    .sale-card { position: relative; overflow: hidden; padding: clamp(28px, 6vw, 66px); border: 1px solid var(--line); border-radius: 30px; background: rgba(255, 255, 255, .96); box-shadow: 0 24px 70px rgba(25, 52, 91, .09); }
    .sale-card::before { position: absolute; right: -110px; top: -118px; width: 330px; height: 330px; border: 1px solid #c1dbf8; border-radius: 50%; background: radial-gradient(circle at 38% 37%, rgba(33, 181, 216, .14), rgba(23, 111, 230, .03) 42%, transparent 65%); content: ""; pointer-events: none; }
    .sale-card::after { position: absolute; right: 82px; top: 72px; width: 96px; height: 96px; border: 1px dashed #96c6f8; border-radius: 50%; content: ""; opacity: .7; pointer-events: none; }
    .eyebrow { position: relative; z-index: 1; display: inline-flex; align-items: center; gap: 8px; color: var(--blue-deep); font-size: 12px; font-weight: 800; letter-spacing: .14em; text-transform: uppercase; }
    .eyebrow::before { width: 8px; height: 8px; border-radius: 2px; background: var(--blue); content: ""; transform: rotate(45deg); }
    h1 { position: relative; z-index: 1; max-width: 760px; margin: 24px 0 0; overflow-wrap: anywhere; font-size: clamp(42px, 8.5vw, 88px); line-height: .93; letter-spacing: -.078em; }
    .available { position: relative; z-index: 1; max-width: 590px; margin: 20px 0 0; color: var(--muted); font-size: clamp(16px, 2vw, 19px); line-height: 1.55; }
    .facts { position: relative; z-index: 1; display: grid; grid-template-columns: minmax(0, 1.1fr) minmax(0, .9fr); gap: 14px; margin-top: 38px; padding-top: 22px; border-top: 1px solid var(--line); }
    .fact { min-height: 126px; padding: 20px; border: 1px solid var(--line); border-radius: 18px; background: linear-gradient(145deg, #fff, #f8fbff); }
    .label { margin: 0; color: var(--muted); font-size: 11px; font-weight: 800; letter-spacing: .12em; text-transform: uppercase; }
    .price { margin: 10px 0 0; font-size: clamp(26px, 4vw, 42px); font-weight: 790; line-height: 1; letter-spacing: -.055em; }
    .description { margin: 10px 0 0; color: var(--muted); font-size: 15px; line-height: 1.65; }
    .actions { position: relative; z-index: 1; display: flex; flex-wrap: wrap; gap: 12px; margin-top: 28px; }
    .button { display: inline-flex; min-height: 50px; align-items: center; justify-content: center; gap: 10px; padding: 0 18px; border: 1px solid transparent; border-radius: 13px; font-size: 15px; font-weight: 760; text-decoration: none; transition: transform .16s ease, box-shadow .16s ease, background .16s ease; }
    .button:hover { transform: translateY(-1px); }
    .button-primary { color: #fff; background: var(--blue); box-shadow: 0 12px 24px rgba(23, 111, 230, .22); }
    .button-primary:hover { background: var(--blue-deep); }
    .button-secondary { border-color: #bdd7f4; color: var(--blue-deep); background: var(--blue-soft); }
    .button-secondary:hover { background: #e2f0ff; box-shadow: 0 9px 18px rgba(23, 111, 230, .09); }
    .route-note { position: relative; z-index: 1; margin: 18px 0 0; color: var(--muted); font-size: 13px; line-height: 1.5; }
    .footnote { display: grid; grid-template-columns: minmax(0, 1fr) auto; gap: 22px; align-items: end; margin-top: 24px; padding: 22px 2px 0; color: var(--muted); font-size: 12px; line-height: 1.65; }
    .powered { color: var(--ink); font-weight: 750; letter-spacing: -.01em; white-space: nowrap; }
    @media (max-width: 640px) { .shell { width: min(100% - 24px, 1040px); padding-top: 20px; } main { margin-top: 42px; } .sale-card { border-radius: 24px; } .facts { grid-template-columns: 1fr; } .fact { min-height: auto; } .footnote { grid-template-columns: 1fr; gap: 10px; } .listing-state { display: none; } }
    @media (prefers-reduced-motion: reduce) { *, *::before, *::after { scroll-behavior: auto !important; transition-duration: 0.01ms !important; animation-duration: 0.01ms !important; } }
  </style>
</head>
<body>
  <div class="shell">
    <header class="topbar">
      <a class="brand" href="https://sajda.dev" aria-label="Sajda">
      <span class="mark" aria-hidden="true">S</span><span>sajda</span>
      </a>
      <span class="listing-state">${escapeSaleLandingHtml(strings.documentEyebrow)}</span>
    </header>
    <main>
      <article class="sale-card">
        <p class="eyebrow">${escapeSaleLandingHtml(strings.documentEyebrow)}</p>
        <h1>${escapedDomain}</h1>
        <p class="available">${escapeSaleLandingHtml(strings.documentAvailable)}</p>
        <div class="facts">
          <section class="fact">
            <p class="label">${escapeSaleLandingHtml(strings.price)}</p>
            <p class="price">${escapedPrice}</p>
          </section>
          <section class="fact">
            <p class="label">${escapeSaleLandingHtml(strings.documentProfile)}</p>
            <p class="description">${escapedDescription}</p>
          </section>
        </div>
        <div class="actions">${listingButton}${contactButton}</div>
        <p class="route-note">${escapeSaleLandingHtml(routeNote)}</p>
      </article>
      <footer class="footnote"><span>${escapeSaleLandingHtml(strings.documentDisclosure)}</span><span class="powered">${escapeSaleLandingHtml(strings.documentPowered)}</span></footer>
    </main>
  </div>
</body>
</html>`;
}

export default function SaleLandingGenerator({
  domain,
  price,
  currency,
  description,
  listingUrl,
  contactUrl,
  className,
}: SaleLandingGeneratorProps) {
  const { language } = useLanguage();
  const strings = saleLandingCopy[language];
  const [downloadStatus, setDownloadStatus] = useState("");
  const [copied, setCopied] = useState(false);
  const [configuredListingUrl, setConfiguredListingUrl] = useState(listingUrl);

  useEffect(() => {
    setConfiguredListingUrl(listingUrl);
  }, [listingUrl]);

  const resolvedDomain = displayDomain(domain);
  const resolvedDescription = description?.trim() || strings.defaultDescription;
  const resolvedPrice = useMemo(
    () => formatListingPrice(price, currency, language, strings.priceOnRequest),
    [currency, language, price, strings.priceOnRequest],
  );
  const resolvedListingUrl = useMemo(() => safeOutboundUrl(configuredListingUrl), [configuredListingUrl]);
  const resolvedContactUrl = useMemo(() => safeOutboundUrl(contactUrl), [contactUrl]);
  const listingUrlIsLocal = isLocalDevelopmentUrl(resolvedListingUrl);
  const isListingDeployable = Boolean(resolvedListingUrl && !listingUrlIsLocal);
  const downloadDocument = useMemo(
    () => createSaleLandingHtml({
      domain: resolvedDomain,
      price: resolvedPrice,
      description: resolvedDescription,
      listingUrl: isListingDeployable ? resolvedListingUrl : null,
      contactUrl: resolvedContactUrl,
      language,
    }),
    [isListingDeployable, language, resolvedContactUrl, resolvedDescription, resolvedDomain, resolvedListingUrl, resolvedPrice],
  );

  const handleDownload = () => {
    const blob = new Blob([downloadDocument], { type: "text/html;charset=utf-8" });
    const objectUrl = URL.createObjectURL(blob);
    const anchor = document.createElement("a");
    anchor.href = objectUrl;
    anchor.download = "index.html";
    anchor.style.display = "none";
    document.body.appendChild(anchor);
    anchor.click();
    anchor.remove();
    window.setTimeout(() => URL.revokeObjectURL(objectUrl), 0);
    setDownloadStatus(strings.downloaded);
  };

  const handleCopyLink = async () => {
    if (!isListingDeployable || !resolvedListingUrl) return;

    try {
      await navigator.clipboard.writeText(resolvedListingUrl);
      setCopied(true);
      window.setTimeout(() => setCopied(false), 1800);
    } catch {
      window.prompt(strings.listingLink, resolvedListingUrl);
    }
  };

  return (
    <section className={cn("overflow-hidden rounded-3xl border border-border bg-card shadow-sm", className)} aria-labelledby="sale-landing-generator-title">
      <div className="flex flex-col gap-4 border-b border-border/80 bg-gradient-to-r from-primary/[0.06] via-card to-card px-5 py-5 sm:flex-row sm:items-start sm:justify-between sm:px-7">
        <div className="min-w-0">
          <div className="flex items-center gap-2 text-xs font-semibold uppercase tracking-[0.14em] text-primary">
            <FileCode2 className="h-4 w-4" aria-hidden="true" />
            {strings.eyebrow}
          </div>
          <h2 id="sale-landing-generator-title" className="mt-2 text-xl font-semibold tracking-tight text-foreground sm:text-2xl">
            {strings.title}
          </h2>
          <p className="mt-2 max-w-2xl text-sm leading-6 text-muted-foreground">{strings.body}</p>
        </div>
        <span className="inline-flex w-fit shrink-0 items-center gap-2 rounded-full border border-primary/15 bg-card px-3 py-1.5 text-xs font-semibold text-primary shadow-sm">
          <FileCode2 className="h-3.5 w-3.5" aria-hidden="true" />
          {strings.ready}
        </span>
      </div>

      <div className="grid gap-5 p-5 lg:grid-cols-[minmax(0,1fr)_minmax(18rem,0.52fr)] lg:gap-7 lg:p-7">
        <div>
          <div className="mb-3 flex items-center justify-between gap-3">
            <p className="text-sm font-semibold text-foreground">{strings.preview}</p>
            <span className="rounded-full border border-border bg-card px-2.5 py-1 text-[0.68rem] font-semibold uppercase tracking-[0.11em] text-muted-foreground">index.html</span>
          </div>

          <div className="overflow-hidden rounded-2xl border border-border bg-[radial-gradient(circle_at_88%_8%,hsl(var(--primary)/0.10),transparent_13rem),#f5f8fc] p-3 sm:p-5">
            <div className="relative overflow-hidden rounded-xl border border-border/85 bg-card p-5 shadow-[0_16px_38px_rgba(29,48,79,0.08)] sm:p-7">
              <div className="pointer-events-none absolute -right-12 -top-16 h-40 w-40 rounded-full border border-primary/20 bg-primary/[0.04]" aria-hidden="true" />
              <div className="relative flex items-center justify-between gap-3">
                <div className="flex items-center gap-2.5 text-sm font-semibold tracking-tight text-foreground">
                  <span className="grid h-8 w-8 place-items-center rounded-lg bg-primary text-sm font-bold italic text-primary-foreground shadow-sm" aria-hidden="true">S</span>
                  sajda
                </div>
                <span className="inline-flex items-center gap-1.5 text-[0.65rem] font-semibold uppercase tracking-[0.12em] text-muted-foreground">
                  <span className="h-1.5 w-1.5 rounded-full bg-emerald-500 ring-4 ring-emerald-500/10" aria-hidden="true" />
                  {strings.documentEyebrow}
                </span>
              </div>

              <div className="relative mt-10 max-w-xl">
                <h3 className="break-words text-4xl font-semibold tracking-[-0.06em] text-foreground sm:text-5xl">{resolvedDomain}</h3>
                <p className="mt-3 text-base leading-7 text-muted-foreground">{strings.documentAvailable}</p>
              </div>

              <div className="relative mt-7 grid gap-3 border-t border-border pt-6 sm:grid-cols-[0.82fr_1.18fr]">
                <div className="rounded-xl border border-border bg-muted/[0.34] p-4">
                  <p className="text-[0.67rem] font-semibold uppercase tracking-[0.11em] text-muted-foreground">{strings.price}</p>
                  <p className="mt-2 text-2xl font-semibold tracking-[-0.045em] text-foreground">{resolvedPrice}</p>
                </div>
                <div className="rounded-xl border border-border bg-muted/[0.2] p-4">
                  <p className="text-[0.67rem] font-semibold uppercase tracking-[0.11em] text-muted-foreground">{strings.documentProfile}</p>
                  <p className="mt-2 whitespace-pre-line text-sm leading-6 text-muted-foreground">{resolvedDescription}</p>
                </div>
              </div>

              <div className="relative mt-6 flex flex-wrap items-center gap-3">
                {isListingDeployable && resolvedListingUrl ? (
                  <a
                    href={resolvedListingUrl}
                    target="_blank"
                    rel="noreferrer"
                    className="inline-flex min-h-11 items-center gap-2 rounded-xl bg-primary px-4 text-sm font-semibold text-primary-foreground shadow-sm transition-colors hover:bg-primary/90 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2"
                  >
                    {strings.documentDirect}
                    <ArrowUpRight className="h-4 w-4" aria-hidden="true" />
                  </a>
                ) : (
                  <span className="inline-flex min-h-11 cursor-not-allowed items-center gap-2 rounded-xl bg-muted px-4 text-sm font-semibold text-muted-foreground" aria-disabled="true">
                    {strings.documentDirect}
                    <ExternalLink className="h-4 w-4" aria-hidden="true" />
                  </span>
                )}
                {resolvedContactUrl ? (
                  <a
                    href={resolvedContactUrl}
                    target="_blank"
                    rel="noreferrer"
                    className="inline-flex min-h-11 items-center gap-2 rounded-xl border border-primary/20 bg-primary/[0.06] px-4 text-sm font-semibold text-primary transition-colors hover:bg-primary/[0.11] focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2"
                  >
                    {strings.documentOffer}
                    <ArrowUpRight className="h-4 w-4" aria-hidden="true" />
                  </a>
                ) : null}
              </div>
              <p className="relative mt-4 text-xs leading-5 text-muted-foreground">{resolvedContactUrl ? strings.documentRoute : strings.documentNoOffer}</p>
            </div>
          </div>
        </div>

        <aside className="flex flex-col rounded-2xl border border-border bg-muted/[0.35] p-5 sm:p-6">
          <div className="flex items-start gap-3">
            <span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-card text-primary shadow-sm ring-1 ring-border/80">
              <Link2 className="h-4.5 w-4.5" aria-hidden="true" />
            </span>
            <div>
              <p className="text-sm font-semibold text-foreground">{strings.listingLink}</p>
              <p className="mt-1 text-sm leading-6 text-muted-foreground">{strings.previewNote}</p>
            </div>
          </div>

          <div className={cn(
            "mt-5 rounded-xl border px-3.5 py-3 text-sm leading-5",
            isListingDeployable ? "border-emerald-200 bg-emerald-50 text-emerald-900" : "border-amber-200 bg-amber-50 text-amber-900",
          )}>
            <div className="flex gap-2">
              <ShieldCheck className="mt-0.5 h-4 w-4 shrink-0" aria-hidden="true" />
              <span>{isListingDeployable ? strings.validLink : listingUrlIsLocal ? strings.localLink : strings.invalidLink}</span>
            </div>
          </div>

          <label className="mt-5 block">
            <span className="text-sm font-semibold text-foreground">{strings.publicListingUrl}</span>
            <input
              type="url"
              value={configuredListingUrl}
              onChange={(event) => setConfiguredListingUrl(event.target.value)}
              placeholder="https://sajda.dev/marketplace/..."
              autoComplete="url"
              spellCheck={false}
              className="mt-2 h-11 w-full rounded-xl border border-input bg-background px-3 text-sm text-foreground outline-none transition-colors placeholder:text-muted-foreground focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2"
            />
            <span className="mt-2 block text-xs leading-5 text-muted-foreground">{listingUrlIsLocal ? strings.localLinkHint : strings.publicListingHint}</span>
          </label>

          {isListingDeployable && resolvedListingUrl ? (
            <Button type="button" variant="outline" onClick={handleCopyLink} className="mt-3 w-full">
              {copied ? <Check className="h-4 w-4" aria-hidden="true" /> : <Copy className="h-4 w-4" aria-hidden="true" />}
              {copied ? strings.copied : strings.copyLink}
            </Button>
          ) : null}

          <div className="mt-5 border-t border-border pt-5">
            <p className="text-sm font-semibold text-foreground">{strings.contactLink}</p>
            <p className="mt-1 text-sm leading-6 text-muted-foreground">{resolvedContactUrl ? strings.contactReady : strings.contactMissing}</p>
          </div>

          <div className="mt-5 rounded-xl border border-border bg-card p-4">
            <p className="text-sm font-semibold text-foreground">{strings.deployTitle}</p>
            <p className="mt-1 text-sm leading-6 text-muted-foreground">{strings.deployBody}</p>
            <ol className="mt-4 space-y-2 text-xs leading-5 text-muted-foreground">
              {[strings.deployStepOne, strings.deployStepTwo, strings.deployStepThree].map((step, index) => (
                <li key={step} className="flex gap-2">
                  <span className="grid h-5 w-5 shrink-0 place-items-center rounded-full bg-primary/[0.08] text-[0.65rem] font-semibold text-primary">{index + 1}</span>
                  <span>{step}</span>
                </li>
              ))}
            </ol>
          </div>

          <p className="mt-5 text-sm leading-6 text-muted-foreground">{strings.disclosure}</p>

          <div className="mt-auto pt-6">
            <Button type="button" onClick={handleDownload} className="w-full" disabled={!isListingDeployable}>
              <Download className="h-4 w-4" aria-hidden="true" />
              {strings.download}
            </Button>
            <p className="mt-3 text-center text-xs leading-5 text-muted-foreground">{strings.downloadHint}</p>
            <p className="sr-only" aria-live="polite" role="status">{downloadStatus}</p>
          </div>
        </aside>
      </div>
    </section>
  );
}
