import { CONNECTOR_HOSTS, CONNECTOR_REVIEWED_AT } from '../shared/connector-catalogue.mjs';
import { connectorConfig, connectorInstallUrl } from '../shared/connector-install.mjs';
const escape = value => String(value).replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');

function hostCard(host, endpoint) {
  const configuration = connectorConfig(host.id, endpoint);
  return `<article class="card" id="host-${host.id}">
    <div class="host-heading"><span class="logo-tile"><img src="${host.logo}" alt="" width="32" height="32"></span><h3>${escape(host.name)}</h3></div>
    <p>${escape(host.steps[0])}</p>
    <a href="${escape(connectorInstallUrl(host.id, endpoint))}" rel="noopener noreferrer" target="_blank">${host.installMethod === 'review-link' ? 'Review connection' : 'Open setup guide'} ↗</a>
    <details><summary>Setup steps & requirements</summary><ol class="steps">${host.steps.map(step => `<li>${escape(step)}</li>`).join('')}</ol>
      <p class="meta">${escape(host.limitation)}</p>
      ${configuration ? `<p class="meta">Merge this with your existing servers. Never replace your full configuration.</p><pre>${escape(configuration)}</pre>` : ''}
      <a class="meta" href="${escape(host.documentation)}" rel="noopener noreferrer" target="_blank">Official instructions ↗</a>
    </details>
  </article>`;
}

/** Script-free: visiting never calls tools, reads an account, or installs a client. */
export function renderConnectorHub(endpoint) {
  const categories = { assistant: 'AI assistants', builder: 'App builders', editor: 'Editors & coding agents' };
  const directory = Object.entries(categories).map(([id, title]) => `<div class="host-group"><h3 class="group-title">${title}</h3><div class="grid">${CONNECTOR_HOSTS.filter(host => host.category === id).map(host => hostCard(host, endpoint)).join('')}</div></div>`).join('');
  return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>Sajda — Names for what you’re building</title><style>
*{box-sizing:border-box}body{margin:0;background:#f4f8ff;color:#152238;font:16px/1.6 system-ui,sans-serif}main{max-width:1140px;margin:auto;padding:40px 22px 64px}h1{font-size:clamp(34px,6vw,62px);line-height:1.08;letter-spacing:-.045em;max-width:820px;margin:20px 0}h2{font-size:clamp(24px,4vw,34px);line-height:1.2;letter-spacing:-.025em;margin:0 0 16px}h3{margin:0 0 10px;font-size:21px}p{max-width:760px}a{color:#075fbb;text-underline-offset:4px}a:focus-visible,summary:focus-visible{outline:3px solid #1475ee;outline-offset:5px}.eyebrow{font-size:13px;letter-spacing:.14em;font-weight:750;color:#1265b5}.lead{font-size:20px;color:#465973;max-width:760px}.button{display:inline-block;background:#1175e9;color:white;border-radius:12px;padding:12px 20px;text-decoration:none;font-weight:650;min-height:48px}.secondary{background:white;color:#075fbb;border:1px solid #aac8eb}.actions{display:flex;flex-wrap:wrap;gap:12px;margin:24px 0}section{margin-top:48px}code,pre{display:block;white-space:pre-wrap;overflow-wrap:anywhere;background:white;border:1px solid #c7d7e9;padding:18px;border-radius:14px;font-size:14px}blockquote{margin:24px 0;padding:22px;border-left:4px solid #1676ed;background:#e7f0ff;font-size:20px;border-radius:0 14px 14px 0}.grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));align-items:start;gap:16px}.card{border:1px solid #ccd9e9;background:white;border-radius:20px;padding:24px;min-width:0}.card p{font-size:15px}.card a{display:inline-block;min-height:44px;padding-top:10px}.meta{font-size:14px;color:#465973}.steps{display:grid;gap:12px;padding-left:24px}.steps li{padding-left:4px}.note{border:1px solid #bad2ef;background:#eaf3ff;border-radius:18px;padding:20px}details{border-top:1px solid #c7d7e9;padding:14px 0}summary{font-weight:650;cursor:pointer;min-height:44px;padding-top:9px}footer{margin-top:48px;border-top:1px solid #c7d7e9;padding-top:20px;font-size:14px}.host-group{margin-top:32px}.group-title{font-size:14px;text-transform:uppercase;letter-spacing:.08em;color:#465973;margin-bottom:14px}.host-heading{display:flex;align-items:center;gap:12px;margin-bottom:16px}.host-heading h3{margin:0;line-height:1.3;overflow-wrap:anywhere}.logo-tile{display:grid;place-items:center;width:48px;height:48px;flex-shrink:0;background:#fff;border:1px solid #e3e9f2;border-radius:12px}.logo-tile img{object-fit:contain}.card pre{padding:12px;font-size:12px}.account-grid{grid-template-columns:repeat(2,minmax(0,1fr))}@media(max-width:800px){.grid{grid-template-columns:repeat(2,minmax(0,1fr))}}@media(max-width:540px){main{padding:28px 18px 48px}.grid{grid-template-columns:1fr}.card{padding:22px}.lead{font-size:18px}.actions .button{width:100%;text-align:center}}
</style></head><body><main>
<header><div class="eyebrow">SAJDA · NAMING INTELLIGENCE</div><h1>Great names. Right where you’re building.</h1><p class="lead">Connect Sajda to your AI assistant or development workspace. Find business names, check domains and compare brand-identity evidence without switching tools.</p><div class="actions"><a class="button" href="#setup">Connect your assistant</a><a class="button secondary" href="#account">Connect your Sajda account</a><a class="button secondary" href="/downloads/sajda-connector.zip" download>Download setup kit</a></div><p class="meta">${CONNECTOR_HOSTS.length} documented client setups. Public searches need no Sajda account. Your host’s plan and permissions still apply.</p></header>
<section id="setup"><h2>1. Choose where you work</h2><p>Add this public MCP server URL. Choose no authentication for public searches. Setup links open a review screen or official guide — they never install anything automatically.</p><code>${escape(endpoint)}</code>${directory}<p class="meta">Other client? Use the same endpoint in a client that supports remote Streamable HTTP MCP. Its authentication, approvals and tool support must be checked separately.</p></section>
<section id="account"><h2>Your account, through your assistant</h2><p>Yes — Sajda also has an authenticated API and MCP server. These are separate from the anonymous search connection above.</p><div class="grid account-grid"><article class="card"><h3>Read your workspace</h3><p>Retrieve saved domains, name projects and membership. Read Trading research and scenarios when your account has Trading access.</p></article><article class="card"><h3>Act with permission</h3><p>Save a shortlist, create a name project or update a scenario. Each action needs the corresponding permission; a read-only key cannot write.</p></article></div><ol class="steps"><li>Sign in to the Sajda app. Open <strong>AI assistants & API → Your API keys</strong>.</li><li>Create an expiring key and select only the permissions you need. New keys do not include account access by default.</li><li>Use the authenticated MCP address shown in that same Sajda workspace. Add the key only to your client’s secure Authorization header field — never to a chat message, URL or repository.</li></ol><div class="note"><strong>Different access, same account.</strong> The public connector cannot access private data. The authenticated service enforces account ownership, permissions and your current plan on every action. Clients without a secure Bearer-header setup need a supported integration; this is not a universal OAuth sign-in claim. A protected Vercel preview is not a publicly usable account connector.</div></section>
<section id="companion"><h2>2. Choose how Sajda helps</h2><div class="grid account-grid"><article class="card"><h3>Ask directly</h3><p>Use Sajda whenever you need it. No extra companion instructions required.</p><blockquote>Use Sajda to find 10 English business names for my logistics app. Check .com and .app domains.</blockquote></article><article class="card"><h3>Get a timely suggestion</h3><p>Optionally add the naming companion from the setup kit to a project or conversation you choose. Your assistant can then offer:</p><blockquote>Would you like Sajda to find 10 business-name ideas for your project and check their domains?</blockquote><a href="/host-instructions.txt">Read the optional instructions ↗</a></article></div><ol class="steps"><li>Your assistant recognises a naming opportunity in context it already has.</li><li>It offers help once. You can say yes, no, or not now.</li><li>After your yes, it sends a short brief and preferences — not your full chat.</li><li>Sajda returns checked candidates, the Brand Index, sources and clear gaps. If only 6 of 10 qualify, the result says why.</li></ol><div class="note"><strong>You stay in control.</strong> Sajda cannot listen to other chats or activate itself. The host controls suggestions. It should not interrupt routine coding, rename an existing project unasked, or repeat an offer after a decline.</div></section>
<section><h2>Know what is — and isn’t — verified</h2><details><summary>Availability, prices and the Brand Index</summary><p>Registry checks do not reserve a domain. Quotes may exclude tax or change before checkout. Extension prices are estimates, not exact-domain offers. Social handles, company records and the Brand Index are not proof of ownership or legal trademark clearance. Unchecked and unknown signals remain labelled.</p></details><details><summary>Client support and directory listings</summary><p>Official setup documentation reviewed ${CONNECTOR_REVIEWED_AT}. This is not a claim of marketplace approval or an end-to-end install test inside every host. Plans, permissions and custom-connector support vary. The downloadable kit and examples do not install themselves.</p><p>Product names and logos identify their respective owners. No endorsement or partnership is implied. <a href="/connectors/LICENSE.txt">Logo asset notices</a>.</p></details><details><summary>Developer resources</summary><p><a href="/connector.json">Machine-readable capability manifest</a> · <a href="/policy.json">Companion policy</a> · <a href="/downloads/sajda-connector.zip">Setup kit</a> · <a href="/downloads/sajda-connector.sha256">SHA-256 checksum</a></p><p>The public MCP exposes six read-only tools, two optional workflow prompts and two static policy resources. Metadata discovery does not start a naming search. Account APIs run on the separate authenticated application backend.</p></details></section>
<footer>Sajda · Landvex AB · <a href="mailto:dev@hypbit.com">Contact Sajda</a>. Shared best-effort limits apply.</footer>
</main></body></html>`;
}
